Parameters:
  KeyName:
    Description: Keypair for SSH access to instance.
    Type: AWS::EC2::KeyPair::KeyName
    Default: ww-vpn
  ConfigBucket:
    Description: S3 bucket where the configuration files are located.
    Type: String
    Default: silly.apps.storage
Resources:
  VpnSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenVPN connections only.
      SecurityGroupIngress:
      - IpProtocol: udp
        FromPort: '1194'
        ToPort: '1194'
        CidrIp: 0.0.0.0/0
  VpnInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
      - !Ref VpnRole
  VpnConfigS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: VpnConfigS3Policy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: !Sub 'arn:aws:s3:::${ConfigBucket}/ww-vpn/*'
        # - Effect: Allow
        #   Principal:
        #     Service:
        #     - ec2.amazonaws.com
        #   Action:
        #   - ecr:GetDownloadUrlForLayer
        #   - ecr:BatchGetImage
        #   - ecr:BatchCheckLayerAvailability
      Roles: 
      - !Ref VpnRole
  VpnRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole 
  Machine:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
      - !Ref VpnSecurityGroup
      - 'SSH Access'
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref VpnInstanceProfile
      ImageId: ami-55ef662f # Amazon Linux 2017.09.1
      InstanceType: t2.small
      UserData: 
        'Fn::Base64': !Sub |
          #!/bin/bash
          yum -y update 
          yum -y install ec2-net-utils docker
          service docker start
          ec2ifup eth1
          mkdir /tmp/clients
          # docker login ...
          docker run --device=/dev/net/tun --cap-add=NET_ADMIN  -v /tmp/clients:/clients 686155034699.dkr.ecr.us-east-1.amazonaws.com/ww-vpn/ww-vpn:latest
          